---

- name: Install json server
  npm: name=json-server global=yes

#- name: Move files
#  shell: cp -r nodejs-database {{databaseDirectory}}
#  args:
#    chdir: "{{gitDirectory}}"

- name: Move files
  copy:
    src:  "{{gitDirectory}}/nodejs-database"
    dest: "{{databaseDirectory}}"
    remote_src: yes


- name: run json server
  shell: json-server --port 5432 db.json 2>&1 </dev/null &
  args:
    chdir: "{{databaseDirectory}}/nodejs-database"