---

- name: Run Todo app 3-tier architecture
  hosts: all
  become: yes

  roles:
    - role: "setup_ubuntu1804"

    - role: "build_angular_app"

    - role: "wrapper_web_server"
      when: force.reboot or force.webserver or gitHasChanged.changed
    
    - role: "deploy_backend"
      when: force.reboot or force.backend or gitHasChanged.changed
    
    - role: "deploy_database"
      when: force.reboot or force.database or gitHasChanged.changed
