---

- name: Print index
  debug:
    msg: Id of webserver is {{loop_index}}

- name: Move configuration nginx
  copy:
    src:  "{{gitDirectory}}/nginx/todo.conf"
    dest: /etc/nginx/conf.d/todo{{loop_index}}.conf
    remote_src: yes

- name: Change port number of webserver conf
  lineinfile:
    path: /etc/nginx/conf.d/todo{{loop_index}}.conf
    regexp: listen 8[0-9] default_server;
    line: listen 8{{loop_index}} default_server;
    firstmatch: yes

- name: Change port number of loadbalancer conf
  lineinfile:
    path: /etc/nginx/conf.d/load-balancer.conf
    regexp: "#server localhost:PORT"
    line: "\tserver localhost:8{{loop_index}};\n\t#server localhost:PORT;"

- name: restart nginx
  service:
    name: nginx
    state: restarted