port:
  web: 4200
  backend: 3000
  database: 5432

nb_instance: 3

gitDirectory: /project
frontendDirectory: /var/www/frontend
backendDirectory: /var/www/backend
databaseDirectory: /var/www/database
