---

- name: Create backend directory
  file: path={{backendDirectory}} state=directory


- name: Move files
  copy:
    src:  "{{gitDirectory}}/nodejs-backend"
    dest: "{{backendDirectory}}"
    remote_src: yes

- name: Run NPM install
  npm: path={{backendDirectory}}/nodejs-backend

- name: Install angular cli package
  npm: name=pm2 global=yes

- name: stop all pm2 process
  shell: pm2 stop all
  ignore_errors: true

- name:
  shell: pm2 start server.js 
  args:
    chdir: "{{backendDirectory}}/nodejs-backend"
  