---

- name: debug
  debug:
    msg: ID of instance is {{loop_index}}

- name: Install dependencies
  apt:
    name:
      - nodejs
      - git
      - npm
      - nginx
      - curl
    update_cache: yes 
    state: latest

- name: Install n package
  npm: name=n global=yes 

- name: Install angular cli package
  npm: name=@angular/cli global=yes

- name: upgrade Node to v12
  shell: n 12

- name: Create frontend directory
  file: path={{frontendDirectory}} state=directory

- name: Git clone repo
  git:
    repo: "https://github.com/LeoPrivate/angular-todo-poc.git"
    dest: "{{gitDirectory}}"
    update: yes
    force: yes
  notify: 
    - "setup frontend"
    - "notify webserver role"

- name: build webserver
  include_role:
    name: deploy_web_server
  when: gitRepositoryHasChanged 

  